[project]
name = "mcp-server-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.0",
    "mcp[cli]>=1.19.0",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
]
